# Generated by Django 4.0.2 on 2022-07-04 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='modelqrp',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order_id', models.IntegerField(default=0)),
                ('name', models.CharField(max_length=15)),
                ('customer_id', models.IntegerField(default=0)),
                ('mobile_no', models.IntegerField(default=0)),
                ('code', models.ImageField(blank=True, upload_to='images')),
            ],
        ),
    ]
