# Generated by Django 4.0.2 on 2022-07-05 07:43

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerate', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='modelqrp',
            new_name='Qrcode',
        ),
    ]
