# Generated by Django 4.0.2 on 2022-07-05 08:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qrgenerate', '0002_rename_modelqrp_qrcode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qrcode',
            name='customer_id',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='mobile_no',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='qrcode',
            name='order_id',
            field=models.IntegerField(),
        ),
    ]
